export const courseData = {
  "full-stack-development": {
    duration: "6 months",
    batchDate: "1st Apr",
    price: "₹34,999",
    oldPrice: "₹45,000",
    discount: "₹10,001",
    rating: 4.5,
    updatedIn: "Jan 26",
    badge: "Guarantee Jobs",
    features: [
      "Get placed with ₹3-10 LPA salary",
      "Course fee refund if not placed",
    ],
    companies: ["SAMSUNG", "xto10x", "haptik"],
    degreeOptions: ["B.Tech", "BCA", "MCA"],
    graduationYears: ["2023", "2024", "2025"],
  },

  "data-science": {
    duration: "5 months",
    batchDate: "10th Apr",
    price: "₹29,999",
    oldPrice: "₹40,000",
    discount: "₹10,001",
    rating: 4.7,
    updatedIn: "Feb 26",
    badge: "Industry-certified",
    features: [
      "Work on real ML projects",
      "Placement assistance included",
    ],
    companies: ["Google", "Amazon", "Flipkart"],
    degreeOptions: ["B.Tech", "B.Sc", "MCA", "M.Tech"],
    graduationYears: ["2023", "2024", "2025", "2026"],
  },
  "captcha-processing": {
    duration: "3 days",
    batchDate: "10th Apr",
    price: "₹1,999*",
    // oldPrice: "₹40,000",
    // discount: "₹10,001",
    rating: 4.7,
    updatedIn: "Feb 26",
    badge: "Guarantee Jobs",
    features: [
      "Get placed with ₹2-6 LPA salary",
      "Work on real Freelancing projects",
      "Placement assistance included",
    ],
   
    degreeOptions: ["B.Tech", "B.Sc", "MCA", "M.Tech"],
    graduationYears: ["2023", "2024", "2025", "2026"],
  },
   "document-conversion": {
    duration: "3 days",
    batchDate: "10th Apr",
    price: "₹1,999*",
    // oldPrice: "₹40,000",
    // discount: "₹10,001",
    rating: 4.7,
    updatedIn: "Feb 26",
    badge: "Guarantee Jobs",
    features: [
      "Get placed with ₹2-7 LPA salary",
      "Work on real Freelancing projects",
      "Placement assistance included",
    ],
   
    degreeOptions: ["B.Tech", "B.Sc", "MCA", "M.Tech"],
    graduationYears: ["2023", "2024", "2025", "2026"],
  },
   "data-segregation": {
    duration: "3 days",
    batchDate: "10th Apr",
    price: "₹1,999*",
    // oldPrice: "₹40,000",
    // discount: "₹10,001",
    rating: 4.7,
    updatedIn: "Feb 26",
    badge: "Guarantee Jobs",
    features: [
      "Get placed with ₹2-7 LPA salary",
      "Work on real Freelancing projects",
      "Placement assistance included",
    ],
   
    degreeOptions: ["B.Tech", "B.Sc", "MCA", "M.Tech"],
    graduationYears: ["2023", "2024", "2025", "2026"],
  },
};

export const defaultCourse = {
  duration: "6 months",
  batchDate: "Coming Soon",
  price: "₹--",
  oldPrice: null,
  discount: null,
  rating: 4.5,
  updatedIn: "Jan 26",
  badge: "Guarantee Jobs",
  features: [
    "Get placed with ₹3-10 LPA salary",
    "Course fee refund if not placed",
  ],
  companies: ["SAMSUNG", "xto10x", "haptik"],
  degreeOptions: ["B.Tech", "BCA", "MCA"],
  graduationYears: ["2023", "2024", "2025"],
};