export const jobs = [
  {
    id: 1,
    title: "Data Entry Operator",
    company: "Gann Analyst",
    activelyHiring: true,
    location: "Delhi",
    stipend: "₹15,000 /month",
    duration: "6 Months",
    profile: "Data Entry Operator",
    tags: ["Back Office", "WFH"],
    postedAgo: "1 day ago",
  },
  {
    id: 2,
    title: "Captcha Verifier",
    company: "Gann Analyst",
    activelyHiring: true,
    location: "Delhi",
    stipend: "₹15,000 /month",
    duration: "6 Months",
    profile: "Captcha Verifier",
    tags: ["Back Office", "WFH"],
    postedAgo: "1 day ago",
  },
  {
    id: 3,
    title: "Data Segregation",
    company: "Gann Analyst",
    activelyHiring: true,
    location: "Delhi",
    stipend: "₹15,000 /month",
    duration: "6 Months",
    profile: "Data Segregation",
    tags: ["Back Office", "WFH"],
    postedAgo: "1 day ago",
  },
  {
    id: 4,
    title: "Computer Operator",
    company: "TechCorp India",
    activelyHiring: true,
    location: "Maharashtra",
    stipend: "₹16,000 /month",
    duration: "6 Months",
    profile: "Computer Operator",
    tags: ["Back Office", "WFH"],
    postedAgo: "3 days ago",
  },
  {
    id: 5,
    title: "Back Office Executive",
    company: "Analytics Hub",
    activelyHiring: false,
    location: "Karnataka",
    stipend: "₹18,000 /month",
    duration: "6 Months",
    profile: "Back Office Executive",
    tags: ["Back Office", "Full Time WFH"],
    postedAgo: "1 week ago",
  },
   {
    id: 6,
    title: "Captcha Verifier",
    company: "Analytics Hub",
    activelyHiring: false,
    location: "Karnataka",
    stipend: "₹18,000 /month",
    duration: "6 Months",
    profile: "Captcha Verifier",
    tags: ["Back Office", "Full Time WFH"],
    postedAgo: "1 week ago",
  },
   {
    id: 7,
    title: "Data Segregation",
    company: "Analytics Hub",
    activelyHiring: false,
    location: "Karnataka",
    stipend: "₹18,000 /month",
    duration: "6 Months",
    profile: "Data Segregation",
    tags: ["Back Office", "Full Time WFH"],
    postedAgo: "1 week ago",
  },
    {
    id: 8,
    title: "Data Conversion Specialist",
    company: "DataWorks Pvt Ltd",
    activelyHiring: true,
    location: "Karnataka",
    stipend: "₹20,000 /month",
    duration: "3 Months",
    profile: "Data Conversion",
    tags: ["Back Office", "Part Time WFH"],
    postedAgo: "2 days ago",
  },
  {
    id: 9,
    title: "Data Conversion Specialist",
    company: "DataWorks Pvt Ltd",
    activelyHiring: true,
    location: "Delhi",
    stipend: "₹20,000 /month",
    duration: "3 Months",
    profile: "Data Conversion",
    tags: ["Back Office", "Part Time WFH"],
    postedAgo: "2 days ago",
  },
  {
    id: 10,
    title: "Graphic Designer Intern",
    company: "Creative Studio",
    activelyHiring: true,
    location: "Maharashtra",
    stipend: "₹25,000 /month",
    duration: "6 Months",
    profile: "Graphic Designer",
    tags: ["Advertsing & Branding", "WFH"],
    postedAgo: "5 days ago",
  },
  {
    id: 6,
    title: "Digital Marketing Executive",
    company: "MarketPro",
    activelyHiring: true,
    location: "Tamil Nadu",
    stipend: "₹22,000 /month",
    duration: "4 Months",
    profile: "Digital Marketer",
    tags: ["Marketing", "Full Time WFH"],
    postedAgo: "1 week ago",
  },
  {
    id: 7,
    title: "Software Developer Intern",
    company: "CodeTech",
    activelyHiring: true,
    location: "Karnataka",
    stipend: "₹40,000 /month",
    duration: "12 Months",
    profile: "Software Developer",
    tags: ["Information Technology", "WFH"],
    postedAgo: "2 days ago",
  },
  {
    id: 8,
    title: "Website Developer",
    company: "Web Solutions",
    activelyHiring: true,
    location: "Telangana",
    stipend: "₹35,000 /month",
    duration: "6 Months",
    profile: "Website Developer",
    tags: ["Information Technology", "WFH"],
    postedAgo: "3 days ago",
  },
  {
    id: 9,
    title: "Video Editor",
    company: "Media House",
    activelyHiring: false,
    location: "Delhi",
    stipend: "₹18,000 /month",
    duration: "3 Months",
    profile: "Video Editor",
    tags: ["Advertsing & Branding", "Part Time WFH"],
    postedAgo: "6 days ago",
  },
  {
    id: 10,
    title: "Big Data Specialist",
    company: "DataMind",
    activelyHiring: true,
    location: "Maharashtra",
    stipend: "₹50,000 /month",
    duration: "12 Months",
    profile: "Big Data Specialist",
    tags: ["Information Technology", "Full Time WFH"],
    postedAgo: "1 day ago",
  },
  {
    id: 11,
    title: "Typist",
    company: "DocuWorks",
    activelyHiring: true,
    location: "Uttar Pradesh",
    stipend: "₹12,000 /month",
    duration: "2 Months",
    profile: "Typiest",
    tags: ["Back Office", "WFH"],
    postedAgo: "4 days ago",
  },
  {
    id: 12,
    title: "Marketing Associate",
    company: "Brandify",
    activelyHiring: true,
    location: "Gujarat",
    stipend: "₹21,000 /month",
    duration: "6 Months",
    profile: "Digital Marketer",
    tags: ["Marketing", "WFH"],
    postedAgo: "2 days ago",
  }
];